name := "OpenStratUser"
version := "0.3.5snap"
scalaVersion := "3.6.3"
libraryDependencies += "dev.zio" %% "zio" % "2.1.16" withSources() withJavadoc()
resolvers += "RichStrat" at "https://richstrat.com/repository"
libraryDependencies += "com.richstrat" % "rutil" % "0.3.5" withSources() withJavadoc()
libraryDependencies += "com.richstrat" % "geom" % "0.3.5" withSources() withJavadoc()
libraryDependencies += "com.richstrat" % "tiling" % "0.3.5" withSources() withJavadoc()
libraryDependencies += "com.richstrat" % "egrid" % "0.3.5" withSources() withJavadoc()